project:
  type: website
  resources: 
    - "favicons/*"
    - "favicon.ico"

website:
  title: "Theory of Probability and Mathematical Statistics"
  navbar: true

format:
  html:
    code-link: true
    code-copy: true
    theme: [cosmo, theme.scss]
    include-in-header: 
      - text: |
          <link rel="apple-touch-icon" sizes="180x180" href="favicons/apple-touch-icon.png">
          <link rel="icon" type="image/png" sizes="32x32" href="favicons/favicon-32x32.png">
          <link rel="icon" type="image/png" sizes="16x16" href="favicons/favicon-16x16.png">
          <link rel="manifest" href="favicons/site.webmanifest">